name: Foundry CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      RPC_URL_ETHEREUM: ${{ secrets.RPC_URL_ETHEREUM }}
      RPC_URL_BASE: ${{ secrets.RPC_URL_BASE }}
      FORK_BLOCK_ETHEREUM: ${{ secrets.FORK_BLOCK_ETHEREUM }}
      FORK_BLOCK_BASE: ${{ secrets.FORK_BLOCK_BASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vvv
